name: Discord Bot CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }} # your bot token from GitHub secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or whichever Node version you use

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node src/bot.js
